#########################
#TOMCAT
#########################
server:
  port: 8088
  tomcat:
    uri-encoding: UTF-8
  max-http-header-size: 80KB
#########################
#配置数据源信息
#########################
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/foodie-shop-dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=true&serverTimezone=UTC
    username: root
    password: 123456
  hikari:
    connection-timeout: 30000
    minimum-idle: 5 #最小链接数
    maximum-pool-size: 20 #最大链接数
    auto-commit: true #自动提交
    idle-timeout: 600000 #链接超时时长
    pool-name: DataSourceHikariCP
    max-lifetime: 1800000
    connection-test-query: SELECT 1

mybatis:
  type-aliases-package: com.imooc.pojo
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
mapper:
  mappers: com.imooc.my.mapper.MyMapper
  not-empty: false
  identity: MYSQL
pagehelper:
  helper-dialect: mysql
  support-methods-arguments: true